// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rentit;

import com.rentit.PurchaseOrder;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PurchaseOrder_Roo_Configurable {
    
    declare @type: PurchaseOrder: @Configurable;
    
}
