// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.rentit.dto;

import com.rentit.dto.OneDate;
import java.util.Calendar;

privileged aspect OneDate_Roo_JavaBean {
    
    public Calendar OneDate.getDate() {
        return this.date;
    }
    
    public void OneDate.setDate(Calendar date) {
        this.date = date;
    }
    
}
