<definitions
	xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
	xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy"
	xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://web.soap.ut.ee/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://web.soap.ut.ee/"
	name="PurchaseOrderSOAPServiceService">
	<types>
		<xsd:schema>
			<xsd:import namespace="http://web.soap.ut.ee/"
				schemaLocation="PurchaseOrderSOAPService.xsd" />
		</xsd:schema>
	</types>
	<message name="setPoStatus">
		<part name="parameters" element="tns:setPoStatus" />
	</message>
	<message name="setPoStatusResponse">
		<part name="parameters" element="tns:setPoStatusResponse" />
	</message>
	<portType name="PurchaseOrderSOAPService">
		<operation name="setPoStatus">
			<input
				wsam:Action="http://web.soap.ut.ee/PurchaseOrderSOAPService/setPoStatusRequest"
				message="tns:setPoStatus" />
			<output
				wsam:Action="http://web.soap.ut.ee/PurchaseOrderSOAPService/setPoStatusResponse"
				message="tns:setPoStatusResponse" />
		</operation>
	</portType>
	<binding name="PurchaseOrderSOAPServicePortBinding" type="tns:PurchaseOrderSOAPService">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"
			style="document" />
		<operation name="setPoStatus">
			<soap:operation soapAction="" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>
	<service name="PurchaseOrderSOAPServiceService">
		<port name="PurchaseOrderSOAPServicePort" binding="tns:PurchaseOrderSOAPServicePortBinding">
			<soap:address
				location="http://buildit-2.herokuapp.com/PurchaseOrderSOAPService?wsdl" />
		</port>
	</service>
</definitions>