package com.rentit.soap.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebService(name = "PurchaseOrderSOAPService", targetNamespace = "http://web.soap.ut.ee/")
@XmlSeeAlso({ ObjectFactory.class })
public interface PurchaseOrderSOAPService {

	/**
	 * 
	 * @param arg0
	 * @return returns com.rentit.soap.client.PoStatusUpdateResponse
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "setPoStatus", targetNamespace = "http://web.soap.ut.ee/", className = "com.rentit.soap.client.SetPoStatus")
	@ResponseWrapper(localName = "setPoStatusResponse", targetNamespace = "http://web.soap.ut.ee/", className = "com.rentit.soap.client.SetPoStatusResponse")
	@Action(input = "http://web.soap.ut.ee/PurchaseOrderSOAPService/setPoStatusRequest", output = "http://web.soap.ut.ee/PurchaseOrderSOAPService/setPoStatusResponse")
	public PoStatusUpdateResponse setPoStatus(
			@WebParam(name = "arg0", targetNamespace = "") PoStatusUpdateRequest arg0);

}
